language: python
python:
  - '3.7'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
 - pip install mypy flake8 black
script:
 - pip install .
 - mypy --ignore-missing-imports todos.py
 - flake8 little_boxes
 - black --check .
